language: python
python:
  - "3.8"
# command to install dependencies
install: "pip install -r requirements.txt"
# command to run tests
script: pytest whalesharkiiot_unit_test.py
services:
  - mongodb
  - redis-server
  - rabbitmq-server
dist: xenial
addons:
  apt:
    sources:
      - ppa:chris-lea/redis-server
    packages:
    - redis-tools
    - redis-server
before_script:
  - sleep 15
  - mongo facility --eval 'db.createUser({user:"whaleshark",pwd:"whaleshark",roles:["readWrite"]});'
  - rabbitmqctl authenticate_user "whaleshark" "whaleshark"
  - rabbitmqctl add_vhost /
