tsdb:
  influx:
    host: '192.168.0.222'
    port: '8086'
    user: ''
    pasword: ''
    dbname: 'whaleshark_iiot'
    protocol: 'json'

mqtt:
  rabbitmq:
    host: 'localhost'
    port: 5672
    id: 'add4sys'
    pwd: 'add4s'

#key: ["value1", "value2"]
#key: value