---
slaves:
- slave1
- slave2
slave1:
  vendor: 'autonics series'
  model_name: 'tk4s'
  stationid: 1
  port: "/dev/tty.usbserial-AQ00WOQH"
  baudrate: 19200
  databits: 8
  parity: 'None'
  stopbits: 2
  timeout: 1.5
  mode: 'rtu'
  pv: 1000
  precision: 1001
  sv: 1003
slave2:
  vendor: 'autonics series'
  model_name: 'tk4s'
  stationid: 2
  port: "/dev/tty.usbserial-AQ00WOQH"
  baudrate: 19200
  databits: 8
  parity: 'None'
  stopbits: 2
  timeout: 1.5
  mode: 'rtu'
  pv: 1000
  precision: 1001
  sv: 1003